services:
  database:
    image: mysql:8.0.4
    container_name: "mysqlAndJava"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: NFMpjTahuttTaEYZKvrBRZjh9
      MYSQL_DATABASE: titan
    ports:
      - "3306:3306"